docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v c:/Users/fajar/Documents/Github/ZoomCamp/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  postgres:13


pgcli -h localhost -p 5432 -u root -d ny_taxi



docker run -it \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="root" \
  -p 8080:80 \
  dpage/pgadmin4

  ## Network

  docker network create pg-network

  docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v c:/Users/fajar/Documents/Github/ZoomCamp/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  --network=pg-network \
  --name pg-database-1 \
  postgres:13


docker run -it \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="root" \
  -p 8080:80 \
  --network=pg-network \
  --name pgadmin \
  dpage/pgadmin4

URL="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"

python ingest_data.py \
--User=root \
--Password=root \
--Host=localhost \
--Port=5432 \
--Database=ny_taxi \
--Table_Name=yellow_taxi \
--url=%{URL}
 
#Create Image
docker build -t taxi_ingest:v001 .

#Run Imaage
docker run -it taxi_ingest:v001 . \
  --network=pg-network \
  taxi_ingest:v001 \
    --User=root \
    --Password=root \
    --Host=localhost \
    --Port=5432 \
    --Database=ny_taxi \
    --Table_Name=yellow_taxi \
    --url=%{URL}


docker-compose up
docker-compose down
Terraform 

1.5.0
python ingest_data.py \

export GOOGLE_APPLICATION_CREDENTIALS=/c/Users/fajar/Downloads/snappy-byte-394006-a54fbaf36ba7.json

export GOOGLE_APPLICATION_CREDENTIALS=/C:/Users/fajar/Downloads/zoomcampproject-394006-efdc7f3eaa8d.json